// @vitest-environment jsdom
import { cleanup, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { HistoryPage } from '../pages/History'
import { ContinueWatchingPage } from '../pages/ContinueWatching'
import { playbackApi } from '../api/playback'
vi.mock('../components/layout/AppLayout', () => ({ AppLayout: ({ children }: any) => children }))
vi.mock('react-i18next', () => ({ useTranslation: () => ({ t: (key: string) => key, i18n: { language: 'en' } }) }))
vi.mock('../api/user', () => ({ userApi: { getHistory: vi.fn().mockResolvedValue({ data: [] }), getWatchlist: vi.fn().mockResolvedValue({ data: [{ contentId: 'saved', title: 'Saved movie', addedAt: '2026-01-01' }] }) } }))
vi.mock('../api/playback', () => ({ playbackApi: { getContinueWatching: vi.fn(), removeFromContinueWatching: vi.fn() } }))
const item = { contentId: 'series-1', title: 'Resume series', episodeId: 's2e3', positionSeconds: 321, durationSeconds: 1000, contentEpisodeId: 'series-1:s2e3', updatedAt: '2026-01-01', type: 'series', s3Thumbnail: null, backdropUrl: null, releaseYear: 2026 }
function Location() { const location = useLocation(); const navigate = useNavigate(); return <><output>{JSON.stringify({ search: location.search, state: location.state })}</output><button onClick={() => navigate(-1)}>Back</button><button onClick={() => navigate(1)}>Forward</button></> }
function mount(path: string) { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><Location /><Routes><Route path="/history" element={<HistoryPage />} /><Route path="/continue-watching" element={<ContinueWatchingPage />} /><Route path="/content/:id" element={<h1>Details</h1>} /></Routes></MemoryRouter></QueryClientProvider>); return client }
afterEach(() => { cleanup(); vi.clearAllMocks() })
describe('library destinations', () => {
  it('opens My List from the URL and follows Back and Forward', async () => { const user = userEvent.setup(); mount('/history?tab=list'); expect(await screen.findByRole('button', { name: 'Saved movie' })).toBeTruthy(); await user.click(screen.getByRole('button', { name: 'history.title' })); expect(screen.queryByRole('button', { name: 'Saved movie' })).toBeNull(); await user.click(screen.getByText('Back')); expect(await screen.findByRole('button', { name: 'Saved movie' })).toBeTruthy(); await user.click(screen.getByText('Forward')); expect(screen.queryByRole('button', { name: 'Saved movie' })).toBeNull() })
  it('resumes with the saved episode and position', async () => { vi.mocked(playbackApi.getContinueWatching).mockResolvedValue({ success: true, data: [item] } as any); const user = userEvent.setup(); mount('/continue-watching'); await user.click(await screen.findByRole('button', { name: 'Resume series' })); expect(screen.getByText('Details')).toBeTruthy(); expect(screen.getByRole('status').textContent).toContain('321'); expect(screen.getByRole('status').textContent).toContain('s2e3') })
  it('restores an optimistic removal when deletion fails', async () => { vi.mocked(playbackApi.getContinueWatching).mockResolvedValue({ success: true, data: [item] } as any); vi.mocked(playbackApi.removeFromContinueWatching).mockRejectedValue(new Error('offline')); const user = userEvent.setup(); mount('/continue-watching'); await screen.findByRole('button', { name: 'Resume series' }); await user.click(screen.getByRole('button', { name: 'common.remove' })); await waitFor(() => expect(screen.getByRole('button', { name: 'Resume series' })).toBeTruthy()); expect(await screen.findByRole('alert')).toBeTruthy() })
  it('invalidates history after a successful removal', async () => { vi.mocked(playbackApi.getContinueWatching).mockResolvedValueOnce({ success: true, data: [item] } as any).mockResolvedValue({ success: true, data: [] }); vi.mocked(playbackApi.removeFromContinueWatching).mockResolvedValue({ success: true, data: null }); const user = userEvent.setup(); const client = mount('/continue-watching'); const invalidate = vi.spyOn(client, 'invalidateQueries'); await screen.findByRole('button', { name: 'Resume series' }); await user.click(screen.getByRole('button', { name: 'common.remove' })); await waitFor(() => expect(invalidate).toHaveBeenCalledWith({ queryKey: ['history', 'local'] })); expect(playbackApi.removeFromContinueWatching).toHaveBeenCalledWith('series-1', 'local'); expect(await screen.findByText('ui.continueWatchingEmpty')).toBeTruthy() })
  it('offers retry when the library cannot load', async () => { vi.mocked(playbackApi.getContinueWatching).mockRejectedValue(new Error('offline')); mount('/continue-watching'); expect(await screen.findByRole('button', { name: 'common.retry' })).toBeTruthy(); expect(screen.queryByText('ui.continueWatchingEmpty')).toBeNull() })
})
